version: "3"

services:
  api_web:
    build: Dockerfile/.
    image: php/7.1.5-apache
    ports:
      - ${HOST_APP_PORT}:80
    volumes:
      - ../.:/var/www/html/
    networks:
      - network
  api_db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - ${HOST_DB_PORT}:3306
    networks:
      - network
networks:
  network:
